 # This is house price prediction competition  dataset on kaggle.

In [1]:
# Import required packages
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
from sklearn import metrics
import numpy as np

In [2]:
# Read data
train= pd.read_csv('train.csv')
test= pd.read_csv('test.csv')
train=train.append(test,ignore_index=True,sort=False)
train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,NaN
2915,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,NaN
2916,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,NaN
2917,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,NaN
2918,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,NaN

In [3]:
# Check null values in each column
train.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            4
LotFrontage       486
LotArea             0
                 ...
MoSold              0
YrSold              0
SaleType            1
SaleCondition       0
SalePrice        1459
Length: 81, dtype: int64

In [4]:
# Information about dataset
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             2919 non-null   int64
 1   MSSubClass     2919 non-null   int64
 2   MSZoning       2915 non-null   object
 3   LotFrontage    2433 non-null   float64
 4   LotArea        2919 non-null   int64
 5   Street         2919 non-null   object
 6   Alley          198 non-null    object
 7   LotShape       2919 non-null   object
 8   LandContour    2919 non-null   object
 9   Utilities      2917 non-null   object
 10  LotConfig      2919 non-null   object
 11  LandSlope      2919 non-null   object
 12  Neighborhood   2919 non-null   object
 13  Condition1     2919 non-null   object
 14  Condition2     2919 non-null   object
 15  BldgType       2919 non-null   object
 16  HouseStyle     2919 non-null   object
 17  OverallQual    2919 non-null   int64
 18  OverallCond    2919 non-null   int64
 19  YearBuilt      2919 non-null   int64
 20  YearRemodAdd   2919 non-null   int64
 21  RoofStyle      2919 non-null   object
 22  RoofMatl       2919 non-null   object
 23  Exterior1st    2918 non-null   object
 24  Exterior2nd    2918 non-null   object
 25  MasVnrType     2895 non-null   object
 26  MasVnrArea     2896 non-null   float64
 27  ExterQual      2919 non-null   object
 28  ExterCond      2919 non-null   object
 29  Foundation     2919 non-null   object
 30  BsmtQual       2838 non-null   object
 31  BsmtCond       2837 non-null   object
 32  BsmtExposure   2837 non-null   object
 33  BsmtFinType1   2840 non-null   object
 34  BsmtFinSF1     2918 non-null   float64
 35  BsmtFinType2   2839 non-null   object
 36  BsmtFinSF2     2918 non-null   float64
 37  BsmtUnfSF      2918 non-null   float64
 38  TotalBsmtSF    2918 non-null   float64
 39  Heating        2919 non-null   object
 40  HeatingQC      2919 non-null   object
 41  CentralAir     2919 non-null   object
 42  Electrical     2918 non-null   object
 43  1stFlrSF       2919 non-null   int64
 44  2ndFlrSF       2919 non-null   int64
 45  LowQualFinSF   2919 non-null   int64
 46  GrLivArea      2919 non-null   int64
 47  BsmtFullBath   2917 non-null   float64
 48  BsmtHalfBath   2917 non-null   float64
 49  FullBath       2919 non-null   int64
 50  HalfBath       2919 non-null   int64
 51  BedroomAbvGr   2919 non-null   int64
 52  KitchenAbvGr   2919 non-null   int64
 53  KitchenQual    2918 non-null   object
 54  TotRmsAbvGrd   2919 non-null   int64
 55  Functional     2917 non-null   object
 56  Fireplaces     2919 non-null   int64
 57  FireplaceQu    1499 non-null   object
 58  GarageType     2762 non-null   object
 59  GarageYrBlt    2760 non-null   float64
 60  GarageFinish   2760 non-null   object
 61  GarageCars     2918 non-null   float64
 62  GarageArea     2918 non-null   float64
 63  GarageQual     2760 non-null   object
 64  GarageCond     2760 non-null   object
 65  PavedDrive     2919 non-null   object
 66  WoodDeckSF     2919 non-null   int64
 67  OpenPorchSF    2919 non-null   int64
 68  EnclosedPorch  2919 non-null   int64
 69  3SsnPorch      2919 non-null   int64
 70  ScreenPorch    2919 non-null   int64
 71  PoolArea       2919 non-null   int64
 72  PoolQC         10 non-null     object
 73  Fence          571 non-null    object
 74  MiscFeature    105 non-null    object
 75  MiscVal        2919 non-null   int64
 76  MoSold         2919 non-null   int64
 77  YrSold         2919 non-null   int64
 78  SaleType       2918 non-null   object
 79  SaleCondition  2919 non-null   object
 80  SalePrice      1460 non-null   float64
dtypes: float64(12), int64(26), object(43)
memory usage: 1.8+ MB

In [5]:
# Impute missing values of continuous variables using KNN Imputer
train1=pd.DataFrame(train.select_dtypes(include=['int32','int64','float64']))

from sklearn.impute import KNNImputer
imputer= KNNImputer(n_neighbors=5,weights="uniform")
train1=pd.DataFrame(imputer.fit_transform(train1))
train1
#train1.fillna(train1.mean(),inplace=True)

,0,1,2,3,4,5,6,7,8,9,...,28,29,30,31,32,33,34,35,36,37
0,1.0,60.0,65.0,8450.0,7.0,5.0,2003.0,2003.0,196.0,706.0,...,0.0,61.0,0.0,0.0,0.0,0.0,0.0,2.0,2008.0,208500.0
1,2.0,20.0,80.0,9600.0,6.0,8.0,1976.0,1976.0,0.0,978.0,...,298.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,2007.0,181500.0
2,3.0,60.0,68.0,11250.0,7.0,5.0,2001.0,2002.0,162.0,486.0,...,0.0,42.0,0.0,0.0,0.0,0.0,0.0,9.0,2008.0,223500.0
3,4.0,70.0,60.0,9550.0,7.0,5.0,1915.0,1970.0,0.0,216.0,...,0.0,35.0,272.0,0.0,0.0,0.0,0.0,2.0,2006.0,140000.0
4,5.0,60.0,84.0,14260.0,8.0,5.0,2000.0,2000.0,350.0,655.0,...,192.0,84.0,0.0,0.0,0.0,0.0,0.0,12.0,2008.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915.0,160.0,21.0,1936.0,4.0,7.0,1970.0,1970.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,2006.0,112700.0
2915,2916.0,160.0,21.0,1894.0,4.0,5.0,1970.0,1970.0,0.0,252.0,...,0.0,24.0,0.0,0.0,0.0,0.0,0.0,4.0,2006.0,119400.0
2916,2917.0,20.0,160.0,20000.0,5.0,7.0,1960.0,1996.0,0.0,1224.0,...,474.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,2006.0,222194.0
2917,2918.0,85.0,62.0,10441.0,5.0,5.0,1992.0,1992.0,0.0,337.0,...,80.0,32.0,0.0,0.0,0.0,0.0,700.0,7.0,2006.0,115600.0
2918,2919.0,60.0,74.0,9627.0,7.0,5.0,1993.0,1994.0,94.0,758.0,...,190.0,48.0,0.0,0.0,0.0,0.0,0.0,11.0,2006.0,226860.0

In [6]:
# Fill missing values of categorical using mode
train['LotFrontage']=train['LotFrontage'].fillna(train['LotFrontage'].mode()[0])
train['BsmtCond']=train['BsmtCond'].fillna(train['BsmtCond'].mode()[0])
train['BsmtQual']=train['BsmtQual'].fillna(train['BsmtQual'].mode()[0])
train['GarageType']=train['GarageType'].fillna(train['GarageType'].mode()[0])
train['GarageFinish']=train['GarageFinish'].fillna(train['GarageFinish'].mode()[0])
train['GarageQual']=train['GarageQual'].fillna(train['GarageQual'].mode()[0])
train['GarageCond']=train['GarageCond'].fillna(train['GarageCond'].mode()[0])
train['GarageYrBlt']=train['GarageYrBlt'].fillna(train['GarageYrBlt'].mode()[0])
train['BsmtExposure']=train['BsmtExposure'].fillna(train['BsmtExposure'].mode()[0])
train['BsmtFinType1']=train['BsmtFinType1'].fillna(train['BsmtFinType1'].mode()[0])
train['BsmtFinType2']=train['BsmtFinType2'].fillna(train['BsmtFinType2'].mode()[0])
train['Electrical']=train['Electrical'].fillna(train['Electrical'].mode()[0])
train['MasVnrType']=train['MasVnrType'].fillna(train['MasVnrType'].mode()[0])
train['MasVnrArea']=train['MasVnrArea'].fillna(train['MasVnrArea'].mean())
train['MSZoning']=train['MSZoning'].fillna(train['MSZoning'].mode()[0])

 # Delete variables having more than 50 percent of missing values

In [7]:
train.drop(['Id','PoolQC','Fence','MiscFeature'],axis=1,inplace=True)

In [8]:
train.drop(['FireplaceQu'],axis=1,inplace=True)

In [9]:
train.drop(['Alley'],axis=1,inplace=True)

# After deleting columns which are having more than 50 percent value we left with the following dimension

In [10]:
train.shape

(2919, 75)

In [11]:
train2=pd.DataFrame(train.select_dtypes(exclude=['int64','float64','int32']))

# Encoding the categorical variables using label encoder

In [12]:
from sklearn.preprocessing import LabelEncoder
number=LabelEncoder()
train['MSZoning']=number.fit_transform(train['MSZoning'].astype('str'))
train['Street']=number.fit_transform(train['Street'].astype('str'))
train['LotShape']=number.fit_transform(train['LotShape'].astype('str'))
train['LandContour']=number.fit_transform(train['LandContour'].astype('str'))
train['Utilities']=number.fit_transform(train['Utilities'].astype('str'))
train['LotConfig']=number.fit_transform(train['LotConfig'].astype('str'))
train['LandSlope']=number.fit_transform(train['LandSlope'].astype('str'))
train['Neighborhood']=number.fit_transform(train['Neighborhood'].astype('str'))
train['Condition1']=number.fit_transform(train['Condition1'].astype('str'))
train['Condition2']=number.fit_transform(train['Condition2'].astype('str'))
train['BldgType']=number.fit_transform(train['BldgType'].astype('str'))
train['HouseStyle']=number.fit_transform(train['HouseStyle'].astype('str'))
train['RoofStyle']=number.fit_transform(train['RoofStyle'].astype('str'))
train['RoofMatl']=number.fit_transform(train['RoofMatl'].astype('str'))
train['Exterior1st']=number.fit_transform(train['Exterior1st'].astype('str'))
train['Exterior2nd']=number.fit_transform(train['Exterior2nd'].astype('str'))
train['MasVnrType']=number.fit_transform(train['MasVnrType'].astype('str'))
train['ExterQual']=number.fit_transform(train['ExterQual'].astype('str'))
train['ExterCond']=number.fit_transform(train['ExterCond'].astype('str'))
train['Foundation']=number.fit_transform(train['Foundation'].astype('str'))
train['BsmtQual']=number.fit_transform(train['BsmtQual'].astype('str'))
train['BsmtCond']=number.fit_transform(train['BsmtCond'].astype('str'))
train['BsmtExposure']=number.fit_transform(train['BsmtExposure'].astype('str'))
train['BsmtFinType1']=number.fit_transform(train['BsmtFinType1'].astype('str'))
train['BsmtFinType2']=number.fit_transform(train['BsmtFinType2'].astype('str'))
train['Heating']=number.fit_transform(train['Heating'].astype('str'))
train['HeatingQC']=number.fit_transform(train['HeatingQC'].astype('str'))
train['CentralAir']=number.fit_transform(train['CentralAir'].astype('str'))
train['Electrical']=number.fit_transform(train['Electrical'].astype('str'))
train['KitchenQual']=number.fit_transform(train['KitchenQual'].astype('str'))
train['Functional']=number.fit_transform(train['Functional'].astype('str'))
train['GarageType']=number.fit_transform(train['GarageType'].astype('str'))
train['GarageFinish']=number.fit_transform(train['GarageFinish'].astype('str'))
train['GarageQual']=number.fit_transform(train['GarageQual'].astype('str'))
train['GarageCond']=number.fit_transform(train['GarageCond'].astype('str'))
train['PavedDrive']=number.fit_transform(train['PavedDrive'].astype('str'))
train['SaleType']=number.fit_transform(train['SaleType'].astype('str'))
train['SaleCondition']=number.fit_transform(train['SaleCondition'].astype('str'))
train['MasVnrType']=number.fit_transform(train['MasVnrType'].astype('str'))

In [13]:
X = train.drop(columns=["SalePrice"],inplace=False, axis=1)

In [14]:
y = pd.DataFrame(train.iloc[:,-1])

In [15]:
train['GarageArea']=train['GarageArea'].fillna(0)
train['GarageCars']=train['GarageCars'].fillna(0)
train['BsmtHalfBath']=train['BsmtHalfBath'].fillna(0)
train['BsmtFullBath']=train['BsmtFullBath'].fillna(0)
train['TotalBsmtSF']=train['TotalBsmtSF'].fillna(0)
train['BsmtUnfSF']=train['BsmtUnfSF'].fillna(0)
train['BsmtFinSF2']=train['BsmtFinSF2'].fillna(0)
train['BsmtFinSF1']=train['BsmtFinSF1'].fillna(0)

In [16]:
train.isnull().sum()

MSSubClass          0
MSZoning            0
LotFrontage         0
LotArea             0
Street              0
                 ...
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice        1459
Length: 75, dtype: int64

# Splitting the data which we have appended in the beggining

In [17]:
final_train=train.iloc[0:1460]
final_train.shape
final_test=train.iloc[1460:2919]
final_test.shape

(1459, 75)

In [18]:
X_train = final_train.drop(columns=["SalePrice"],inplace=False, axis=1)
X_train.shape

(1460, 74)

In [19]:
y_train = pd.DataFrame(final_train.iloc[:,-1])
y_train.shape

(1460, 1)

In [20]:
X_test = final_test.drop(columns=["SalePrice"],inplace=False, axis=1)

# After data cleaning we now proceed to model fitting. Here, we use Random Forest Regressor to predict Sale Price of house

In [21]:
from sklearn.ensemble import RandomForestRegressor
from pprint import pprint
reg=RandomForestRegressor()
reg.fit(X_train,y_train)
y_pred=pd.DataFrame(reg.predict(X_test))

<ipython-input-21-cf2f6a765051>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  reg.fit(X_train,y_train)

In [22]:
reg.feature_importances_

array([1.24767895e-03, 2.01031640e-03, 5.77743533e-03, 1.24702132e-02,
       5.76068947e-06, 1.53597082e-03, 1.89791358e-03, 6.16346914e-07,
       7.77840511e-04, 5.30356226e-04, 6.71431921e-03, 1.01005156e-03,
       3.06777150e-04, 2.24084306e-04, 7.61178217e-04, 5.75419075e-01,
       4.69880278e-03, 9.71731704e-03, 6.83465827e-03, 9.12152626e-04,
       1.36634532e-04, 2.08045632e-03, 1.15568287e-03, 1.38706059e-03,
       4.48547389e-03, 3.33863532e-03, 4.97397052e-04, 3.75044936e-04,
       5.71904512e-03, 2.78900373e-04, 2.29816897e-03, 1.65922791e-03,
       2.70604390e-02, 1.91881740e-04, 3.43363527e-04, 6.34750177e-03,
       4.51149227e-02, 1.60640948e-04, 6.72660348e-04, 2.99495752e-03,
       1.54358065e-04, 2.46103097e-02, 3.07819576e-02, 7.00556946e-05,
       1.11051069e-01, 9.08228220e-04, 1.53564013e-04, 4.36358341e-03,
       9.32086559e-04, 2.10806694e-03, 9.18864122e-04, 2.29707718e-03,
       8.79561906e-03, 4.80865869e-04, 3.34494719e-03, 3.30995285e-03,
       4.26725699e-03, 4.53919112e-03, 1.96314049e-02, 1.66766195e-02,
       1.92761932e-04, 1.19943781e-04, 3.26833364e-04, 4.51941245e-03,
       4.72783981e-03, 8.13328502e-04, 1.54957655e-04, 1.63311440e-03,
       1.04899829e-03, 6.01192777e-05, 3.34004913e-03, 1.55903241e-03,
       8.77583478e-04, 2.08033360e-03])

In [23]:
from sklearn.model_selection import RandomizedSearchCV

In [24]:
n_estimators = [int(x) for x in np.linspace(start=100, stop=1000, num=10)]
max_features=['auto','sqrt']
max_depth= [int(x) for x in np.linspace(start=100, stop=1000, num=10)]
max_depth.append(None)
min_samples_leaf=[1,2,4]
min_samples_split=[2,5,10]
n_estimators

[100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]

In [25]:
random_grid={'n_estimators':n_estimators,
            'max_features':max_features,
            'max_depth':max_depth,
            'min_samples_split':min_samples_split,
            'min_samples_leaf':min_samples_leaf}

In [26]:
reg=RandomForestRegressor()
reg

RandomForestRegressor()

In [27]:
reg_random=RandomizedSearchCV(estimator=reg,param_distributions=random_grid,n_iter=100,verbose=2,random_state=0)

In [28]:
reg_random

RandomizedSearchCV(estimator=RandomForestRegressor(), n_iter=100,
                   param_distributions={'max_depth': [100, 200, 300, 400, 500,
                                                      600, 700, 800, 900, 1000,
                                                      None],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [100, 200, 300, 400,
                                                         500, 600, 700, 800,
                                                         900, 1000]},
                   random_state=0, verbose=2)

In [29]:
#reg_random.fit(X_train,y_train)

In [32]:
# after hyper parameter tuning
reg_random = RandomForestRegressor(n_estimators=600,min_samples_split=10,min_samples_leaf=1,max_features='sqrt',max_depth=900,)

In [34]:
reg_random.fit(X_train,y_train)
y_pred=pd.DataFrame(reg_random.predict(X_test))
y_pred

<ipython-input-34-0769fc095ef8>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  reg_random.fit(X_train,y_train)

                  0
0     128540.912721
1     152192.179641
2     182465.844055
3     185748.947368
4     199043.505998
...             ...
1454   90442.202448
1455   93098.253982
1456  162862.483694
1457  124032.981377
1458  230983.615685

[1459 rows x 1 columns]

In [ ]:
import pickle
filename= 'finalised_model.pkl'
pickle.dump(reg_random,open(filename,'wb'))

In [ ]:
sub_data=pd.read_csv('sample_submission.csv')

In [ ]:
dataset=pd.concat([sub_data['Id'],y_pred],axis=1)

In [ ]:
dataset.columns=['Id','SalePrice']

In [ ]:
dataset.to_csv('sample_submission.csv',index=False)